### ISSUE TITLE
Functionality included in KWin 5.26

### ISSUE THREAD

**Issue by Zamundaaa** [Hegemonia123/restoreToScreen#2]
Hey there! I see that we both worked on solving the same problem. With 5.26, KWin core now attempts to move windows back on screen layout changes. So if you see this no longer working the same with 5.26, that might be the cause.
Also, if the included fix in KWin doesn't work as you need it to or is buggy, please do make suggestions and/or bug reports! Ideally it should "just work" out of the box for all users

**Comment by Hegemonia123** [comment]
Hi! Thanks for letting me know. I noticed some issue a while ago and had to implement a hacky workaround by undoing the moves kwin makes automatically. Another laptop of mine is running older version of Kwin, so I will be stuck with this script for a while. 

I tried 5.26 without this script but the inbuilt feature doesn't seem to work. Windows are not moved back to external monitor when I reconnect it. Or did I misunderstand how the feature should work?

**Comment by Zamundaaa** [comment]
Windows you moved or resized since the monitor has been unplugged are left alone, the assumption is that you intentionally modified them and want to keep them that way. For those that you didn't it should always move them back though

**Comment by Hegemonia123** [comment]
OK. I still wasn't able to make it work, but windows stay on the laptop screen when external monitor is reconnected regardless of have I moved them or not. 

As a improvement idea, maybe windows should be restored even if they are moved after disconnecting the screen. At least I usually like to organize windows differently when I'm using only laptop screen.

**Comment by Zamundaaa** [comment]
It looks like a bug has sneaked in that made windows not be restored most of the time, unless you unplugged the output they were on. So that might be the cause of what you're seeing.

> As a improvement idea, maybe windows should be restored even if they are moved after disconnecting the screen. At least I usually like to organize windows differently when I'm using only laptop screen.

The problem is that we don't know what the user really wants, so we pretty much need to stay conservative on automatically "helping" to not annoy people. I can definitely see why you'd want it, adding an option for this might be a good idea.

**Comment by Hegemonia123** [comment]
> The problem is that we don't know what the user really wants, so we pretty much need to stay conservative on automatically "helping" to not annoy people. I can definitely see why you'd want it, adding an option for this might be a good idea.

You might be right. The option sounds good.
